apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: 10M
    nginx.ingress.kubernetes.io/proxy-body-size: 10M
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    service: nginx-ingress-lb
  loadBalancerIP: {{ .Values.loadBalancerIP }}
